// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_CvzonJkcqYK_psB1IxyLnbIe0eparE4',
    appId: '1:925055549955:web:cfada53c8c106fa96e0436',
    messagingSenderId: '925055549955',
    projectId: 'instagramclone-cceb0',
    authDomain: 'instagramclone-cceb0.firebaseapp.com',
    storageBucket: 'instagramclone-cceb0.appspot.com',
    measurementId: 'G-FVJCFKNX52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-7r3yMoE1-pWG0pFlgMBta30VKAWVDM',
    appId: '1:925055549955:android:6a02d973c24c75d26e0436',
    messagingSenderId: '925055549955',
    projectId: 'instagramclone-cceb0',
    storageBucket: 'instagramclone-cceb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeg57ZT7lDFxl7xgL7qmQX77Cg7TQPYVg',
    appId: '1:925055549955:ios:a94d79423bce889b6e0436',
    messagingSenderId: '925055549955',
    projectId: 'instagramclone-cceb0',
    storageBucket: 'instagramclone-cceb0.appspot.com',
    androidClientId: '925055549955-943edmqds8suj3isgeqe2gari79q7quc.apps.googleusercontent.com',
    iosClientId: '925055549955-f7qbgr8gj98k7l0au7d6ctg6c6pe5ccl.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagrampj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeg57ZT7lDFxl7xgL7qmQX77Cg7TQPYVg',
    appId: '1:925055549955:ios:74fe73b6d365802e6e0436',
    messagingSenderId: '925055549955',
    projectId: 'instagramclone-cceb0',
    storageBucket: 'instagramclone-cceb0.appspot.com',
    androidClientId: '925055549955-943edmqds8suj3isgeqe2gari79q7quc.apps.googleusercontent.com',
    iosClientId: '925055549955-imjs28o1ni9g7ls9hja014aj5stquqn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagrampj.RunnerTests',
  );
}
